//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chamcong
    {
        public int MaChamCong { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> ThoiGianVao { get; set; }
        public Nullable<System.TimeSpan> ThoiGianRa { get; set; }
        public string Scan { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
