//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;


    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.chamcongs = new HashSet<chamcong>();
        }
        public bool IsValidRole()
        {
            return !string.IsNullOrEmpty(PhanQuyen) && (PhanQuyen == "Admin" || PhanQuyen == "User");
        }


        public int MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public string Email { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public Nullable<int> MaPhongBan { get; set; }
        public string Password { get; set; }
        public string PhanQuyen { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chamcong> chamcongs { get; set; }
        public virtual chucvu chucvu { get; set; }
        public virtual phongban phongban { get; set; }
        public string TenChucVu { get; set; }
        public string TenPhongBan { get; set; }
    }
}
